version: '3'
services:
  pcapcopier_v1.7:
    ports:
      - "127.0.0.1:2022:2022"
    volumes:
      - "/home/silentdefense:/home/silentdefense"
      - "/var/log/pcapcopier:/var/log/pcapcopier"
      - "/opt/nids-docker/custom/pcaps/sniff_offline/:/opt/nids-docker/custom/pcaps/sniff_offline/"
    container_name: pcapcopier_v1.7
    image: pcapcopier_v1.7
    restart: unless-stopped
